name: discord-github-action

on:
  pull_request:
  push:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: discord-notification-action
        uses: ./.github/actions/discord-notification
